# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'play.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(923, 652)
        Form.setStyleSheet("background-color: rgb(39,71,133);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setStyleSheet("color: white;\n"
"font-size: 80px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setStyleSheet("color: white;\n"
"font-size: 80px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("color: white;\n"
"font-size: 80px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setStyleSheet("color: white;\n"
"font-size: 80px;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setStyleSheet("color: red;\n"
"font-size: 80px;\n"
"border: 2px solid red;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setStyleSheet("background-color: rgb(89, 255, 71);\n"
"color: white;\n"
"font-size: 30px;\n"
"border-radius: 30px;")
        self.pushButton_3.setIconSize(QtCore.QSize(30, 50))
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_7.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setStyleSheet("background-color: rgb(89, 255, 71);\n"
"color: white;\n"
"font-size: 30px;\n"
"border-radius: 30px;")
        self.pushButton_5.setIconSize(QtCore.QSize(30, 50))
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_7.addWidget(self.pushButton_5, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setStyleSheet("background-color: rgb(89, 255, 71);\n"
"color: white;\n"
"font-size: 30px;\n"
"border-radius: 30px;")
        self.pushButton_4.setIconSize(QtCore.QSize(30, 50))
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_7.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setStyleSheet("background-color: rgb(89, 255, 71);\n"
"color: white;\n"
"font-size: 30px;\n"
"border-radius: 30px;")
        self.pushButton_6.setIconSize(QtCore.QSize(30, 50))
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_7.addWidget(self.pushButton_6, 0, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setStyleSheet("background-color: rgb(89, 255, 71);\n"
"color: white;\n"
"font-size: 30px;\n"
"border-radius: 30px;")
        self.pushButton_7.setIconSize(QtCore.QSize(30, 50))
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_7.addWidget(self.pushButton_7, 2, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setStyleSheet("background-color: rgb(89, 255, 71);\n"
"color: white;\n"
"font-size: 30px;\n"
"border-radius: 30px;")
        self.pushButton_8.setIconSize(QtCore.QSize(30, 50))
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_7.addWidget(self.pushButton_8, 2, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setStyleSheet("background-color: rgb(89, 255, 71);\n"
"color: white;\n"
"font-size: 30px;\n"
"border-radius: 30px;")
        self.pushButton_9.setIconSize(QtCore.QSize(30, 50))
        self.pushButton_9.setFlat(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_7.addWidget(self.pushButton_9, 3, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setStyleSheet("background-color: rgb(89, 255, 71);\n"
"color: white;\n"
"font-size: 30px;\n"
"border-radius: 30px;")
        self.pushButton_10.setIconSize(QtCore.QSize(30, 50))
        self.pushButton_10.setFlat(False)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_7.addWidget(self.pushButton_10, 3, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setStyleSheet("background-color: rgb(89, 255, 71);\n"
"color: white;\n"
"font-size: 30px;\n"
"border-radius: 30px;")
        self.pushButton_2.setIconSize(QtCore.QSize(30, 50))
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_7.addWidget(self.pushButton_2, 4, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setStyleSheet("background-color: rgb(89, 255, 71);\n"
"color: white;\n"
"font-size: 30px;\n"
"border-radius: 30px;")
        self.pushButton.setIconSize(QtCore.QSize(30, 50))
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_7, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "1"))
        self.label_3.setText(_translate("Form", "+"))
        self.label.setText(_translate("Form", "2"))
        self.label_4.setText(_translate("Form", "="))
        self.label_5.setText(_translate("Form", "?"))
        self.pushButton_3.setText(_translate("Form", "4"))
        self.pushButton_5.setText(_translate("Form", "8"))
        self.pushButton_4.setText(_translate("Form", "1"))
        self.pushButton_6.setText(_translate("Form", "9"))
        self.pushButton_7.setText(_translate("Form", "5"))
        self.pushButton_8.setText(_translate("Form", "6"))
        self.pushButton_9.setText(_translate("Form", "2"))
        self.pushButton_10.setText(_translate("Form", "3"))
        self.pushButton_2.setText(_translate("Form", "0"))
        self.pushButton.setText(_translate("Form", "7"))
